# Generated by Django 3.1.5 on 2021-01-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('masterpiece', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PerformerInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('birth', models.CharField(max_length=20)),
                ('elapse', models.CharField(max_length=20)),
                ('performer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.performer')),
            ],
        ),
    ]
